### ISSUE TITLE
[SPEC] Cleanup wasm-utils

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb.js#104]
The purpose of wasm-utils is to bridge the rust world of zero-knowledge proofs and javascript frontend app. It should use an API provided from arkworks-gadgets to generate proofs and have its own functionality for managing notes.

The order of actions on the frontend for deposit:
1. Generate: secret, nullified and a leaf - this is done with a function provided by arkworks which is wrapped around wasm_bindgen and return them to javascript
2. Insert a leaf into the tree on-chain
3. Create the note with nullified and secret + other relevant data
4. Present the note to the user

For withdraw:
1. The note is provided by the user
2. Pass the note into wasm-utils, deserialize it
3. Pass other data needed to generate proof: recipient, relayer, leaves, leaf_index, fee, refund, proving_key
4. Generate the proof and return proof_bytes, root, nullifier_hash

There are 3 structs we need: `Note`, `ProofInput`, `Proof`. Each of them will have a JS equivalent (`JsNote`, `JsProofInput`, `Proof`)

For easier construction, we will have Builders for Note and ProofInput (NoteBuilder and ProofInputBuilder respectively).

For note:
Have a NoteBuilder that builds JsNote:
```rust
struct NoteBuilder {
    pub version: Option<NoteVersion>,
    pub secrets: Option<Vec<u8>>,
   ...
}

impl NoteBuilder {
	pub fn version(&mut self, version: Version) {
		let c: String = JsValue::from(&version).as_string().unwrap();
		self.version = Some(c.parse().unwrap());
	}

	#[wasm_bindgen(js_name= setSecrets)]
	pub fn set_secrets(&mut self, secrets: JsString) {
		let secrets_string: String = secrets.into();
		let sec = hex::decode(secrets_string.replace("0x", "")).unwrap();
		self.note_builder.secrets = Some(sec);
	}

      pub fn build(self) -> Result<JsNote, OpStatusCode> {
          if self.version.is_none() {
              return Err(OpStatusCode::InvalidNoteVersion);
          }

          let version = self.version.unwrap();

          return JsNote::new(version, ...);
      }
}
```

We should have two versions of the note, the rust version and wasm_bindgen version to be used by Javascript:
Rust Version:
```rust
pub struct Note {
	pub prefix: NotePrefix,
	pub version: NoteVersion,
	pub chain_id: String,
	pub source_chain_id: String,

	/// zkp related items
	pub backend: Backend,
	pub hash_function: HashFunction,
	pub curve: Curve,
	pub exponentiation: i8,
	pub width: usize,
	/// mixer related items
	pub secret: Vec<u8>,

	pub token_symbol: String,
	pub amount: String,
	pub denomination: u8,
}

impl Note {
    // Getters and Setters
   fn serialize(&self) -> String;
   fn deserialize(note_str: String) -> Note;
}
```
Javascript version -- just a wrapper around Note:
```rust
#[wasm_bindgen]
struct JsNote {
    note: Note,
}

impl JsNote {
    // Getters
   fn serialize(&self) -> JsString;
   fn deserialize(note_str: JsString) -> JsNote;
}
```

For ProofInput:
```rust
pub struct ProofInput {
	recipient: Vec<u8>,
	relayer: Vec<u8>,
	leaves: Vec<[u8; 32]>,
	leaf_index: u32,
	fee: u32,
	refund: u32,
	note: Note,
	pk: Vec<u8>,
}

#[wasm_bindgen]
pub struct JsProofInput {
    proof_input: ProofInput,
}

impl JsProofInput {
    // Getters
}

// ProofInput builder
pub struct ProofInputBuilder {
    	recipient: Option<Vec<u8>>,
	relayer: Option<Vec<u8>>,
	leaves: Option<Vec<[u8; 32]>>,
	leaf_index: Option<u32>,
	fee: Option<u32>,
	refund: Option<u32>,
	note: Option<Note>,
	pk: Option<Vec<u8>>,
}
```

For Leaf:
```rust
#[wasm_bindgen]
pub struct Leaf {
	#[wasm_bindgen(skip)]
	pub leaf: String,
	#[wasm_bindgen(skip)]
	pub nullifier: String,
	#[wasm_bindgen(skip)]
	pub secret: String,
}

#[wasm_bindgen]
impl Leaf {
	#[wasm_bindgen(getter)]
	pub fn leaf(&self) -> JsString {
		self.leaf.clone().into()
	}

	#[wasm_bindgen(getter)]
	pub fn nullifier(&self) -> JsString {
		self.nullifier.clone().into()
	}

	#[wasm_bindgen(getter)]
	pub fn secret(&self) -> JsString {
		self.secret.clone().into()
	}
}

#[wasm_bindgen]
fn generate_leaf_js() -> Leaf {
    // Call create_leaf_x5 or similar from arkworks, convert result into JsLeaf
}
```

For Proof and JsProof
```rust
#[wasm_bindgen]
pub struct Proof {
	#[wasm_bindgen(skip)]
	pub proof: String,
	#[wasm_bindgen(skip)]
	pub nullifier_hash: String,
	#[wasm_bindgen(skip)]
	pub root: String,
}

#[wasm_bindgen]
impl Proof {
	#[wasm_bindgen(getter)]
	pub fn proof(&self) -> JsString {
		self.proof.clone().into()
	}

	#[wasm_bindgen(getter)]
	pub fn nullifier_hash(&self) -> JsString {
		self.nullifier_hash.clone().into()
	}

	#[wasm_bindgen(getter)]
	pub fn root(&self) -> JsString {
		self.root.clone().into()
	}
}

#[wasm_bindgen]
fn generate_proof_js(note: JsNote, proof_input: JsProofInput) -> Proof {
    // Get the values from note and proof_input and convert them to rust types
    // Call generate_proof from arkworks gadgets repo which returns proof (Vec<u8u>), nullified (Vec<u8>), root (Vec<u8>)
}
```

Requirements from arkworks-gadgets:
1. Have a function that is going to create a random secret, nullified, and the leaf, and is going to return all three of them. We should have a wasm wrapper around this function that returns `Uint8Array`.
2. Have a function or set of functions that generate proof given the Note and ProofInput. Have a wasm wrapper that returns the Proof struct

Checklist:
- [x] #111
- [x] #112

**Comment by filiplazovic** [comment]
@AhmedKorim Feel free to add ideas on how to have a minimum amount of structs that satisfies both Rust and Js.
The most important thing for me is `generate_proof` and `create_leaf_x5` to be used instead of creating the proof in wasm utils.

**Comment by filiplazovic** [comment]
This has to be implemented https://github.com/webb-tools/arkworks-gadgets/issues/92, before doing this task

**Comment by drewstone** [comment]
*   [ ] test
