### ISSUE TITLE
[SPEC] Legacy note support

### ISSUE THREAD

**Issue by nepoche** [webb-tools/webb.js#134]
### Overview

As the NoteInput changes - so does the parsing logic for the text field where a user pastes the note for withdrawal interaction. It is crucial that legacy notes for live networks maintain withdraw functionality in the dapp.

### Pattern for implementing incremental updates to the Note structure

The most obvious place to determine which parsing logic to use would be to look at the version of the note. Depending on the version, different actions can be taken to morph the note object into the expected, latest versioned structure - before a final call to `wasm.JsNote.deserialize(value)` is made. This would include an API change of the deserialize() method of the note from `static deserialize(value: string)` to `static deserialize(value: string, version: number)`. Logic for how to change from the specified `version` to a format that the latest webb.js understands would need to be added in webb.js.

Pros:
- webb-dapp doesn't change based upon webb.js changes to note structure.

Cons:
- Requires an assumption about note structure in order to parse for the version number before calling `deserialize`.

### Ideas for ensuring backwards compatibility

Tests in the webb.js repo for deserialization of legacy note strings.

**Comment by nepoche** [comment]
From the webb.js perspective, legacy notes are supported.

From the dapp perspective, legacy notes for tornados are supported, but bridges yet been supported.

**Comment by dutterbutter** [comment]
Closed in #169
