### ISSUE TITLE
Integrate Circom, direct JS/TS note generation + proving in the sdk-core

### ISSUE THREAD

**Issue by drewstone** [webb-tools/webb.js#211]
# Overview
We currently support generating notes using the WASM functions that call into Arkworks. We do not however have the note work for the Circom backend integrated in a separate flow. Last I checked this is being done on the fly in the dApp or in the api providers.

# Task
We should add this flow into `sdk-core`. That is, when someone specifies a note generation input with `Circom` as the proving backend, we will call the functionality to generate the note using the dedicated JS/TS functions rather than the WASM work.

**Comment by drewstone** [comment]
Please comment if there's questions/inconsistencies @nepoche @AhmedKorim ?

**Comment by dutterbutter** [comment]
Closed in https://github.com/webb-tools/webb.js/pull/239
