### ISSUE TITLE
[Task] Decorate `lt_getNeighborEdges` for substrate api

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb.js#222]
# Overveiw
Polkadot API option don't have the type decoration for RPC method `lt_getNeighborEdges`

**Comment by dutterbutter** [comment]
@AhmedKorim please provide additional details to this issue.

**Comment by AhmedKorim** [comment]
this was related to decorating the RPC method, and this is already done in tests and the dApp
