### ISSUE TITLE
[CI] [Docs] Run docs build for PRs CI

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb.js#234]
**Is your feature request related to a problem? Please describe.**
Some type issues will cause type doc to fail on `master` to build the docs, thus fail to build

**Describe the solution you'd like**
Tweak CI to run doc building on PRs CI

**Describe alternatives you've considered**
Split docs / `webb.js` publishing

**Additional context**
`Webb.js` publishing don't work since this PR https://github.com/webb-tools/webb.js/pull/232

**Comment by nepoche** [comment]
docs and webb.js publishing are split, and new builds of webb.js are able to be published. This issue is still useful to track the failure of docs generation. Perhaps as a workaround we can try not to include the `@webb-tools/types` package for docs generation.

**Comment by dutterbutter** [comment]
@nepoche @AhmedKorim the docs will pass if add `// @ts-nocheck` to `packages/types/src/interfaces/types-lookup.ts`. I had done this in the past but because they are auto generated I guess it had removed it?
