### ISSUE TITLE
[Error] after depositing to the mixer RPC call return error

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb.js#24]
Error 

 index.js:1 2021-02-24 15:07:11        REGISTRY: Error: Call: failed decoding mixer.deposit:: Struct: failed on args: {“mixer_id”:“GroupId”,“data_points”:“Vec<Data>“}:: Struct: failed on data_points: Vec<Data>:: Cannot map Enum JSON, unable to find ‘0’ in none, raw, blaketwo256, sha256, keccak256, shathree256

call params

```
Args for TXButton[
  0,
  [
    [
      196,
      149,
      16,
      90,
      89,
      129,
      240,
      148,
      82,
      170,
      240,
      94,
      113,
      251,
      252,
      159,
      117,
      168,
      232,
      37,
      204,
      63,
      223,
      242,
      55,
      148,
      112,
      64,
      172,
      128,
      62,
      7
    ]
  ]
]
```

**Comment by shekohex** [comment]
I guess this could be closed now!
