### ISSUE TITLE
[TASK] Remove all Fixed Anchor references and update tests accordingly 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/webb.js#252]
## Overview

We are deprecating the fixed anchor and should remove all unnecessary code from this repo that references anchor. Tests will need to be updated and fixed accordingly. 

### Tasks

- [ ] Remove all fixed anchor references
- [ ] Update tests that utilize fixed anchor

**Comment by drewstone** [comment]
We don't need to remove all references @dutterbutter for now, but I did update the note tests and remove tests of fixed anchor.
