### ISSUE TITLE
[BUG] Docker container cleanup for tests ,and slowing down

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb.js#261]
**Describe the bug**
Make sure that we do a sufficient cleanup for the docker container once the test is done, as we noticed after the addition of wrap/unwrap tests the docker container running the node slowed down leading to test time increase thus failure of tests while being valid

**Expected behavior**
- Docker container/networks cleanup after a test is done
- Running an integration test utilizing the docker image for the node shouldn't be effect be the number of them or the order of that test

**Additional context**
#259

**Comment by AtelyPham** [comment]
This issue is now closed as it has become outdated.
