### ISSUE TITLE
[TASK] Expose different types for different runtimes

### ISSUE THREAD

**Issue by nepoche** [webb-tools/webb.js#264]
- Multi-types package for different deployments (i.e. Tangle, Protocol-substrate, dkg-substrate separated).
    - Goal
        - have users that only require interaction with protocol-substrate (no dkg) to create api instances that use vAnchor types.
            - i.e. `import '@webb-tools/types/protocol-substrate`
    - tasks
        - expose yarn scripts with cli arguments for calling into types generation scripts to support different folder type generation output.
        - Update relevant scripts
    - Cons
        - Anyone importing the types package will download all deployment types. Could be large?
            - Since it's mostly types, it won't add to bundle size - just repo size.

**Comment by AhmedKorim** [comment]
We can add the types to the include types so we don't have to import the types while using the API

```json
{
...
  "include": [
	"@webb-tools/types",
    "src/**/*",
    "node_modules/@subql/types/dist/global.d.ts"
  ],
..
}


```

**Comment by AtelyPham** [comment]
This issue is now closed as it has become outdated.
