### ISSUE TITLE
[Mixer-thread] [withdraw] Adding leaves fails

### ISSUE THREAD

**Issue by AhmedKorim** [webb-tools/webb.js#40]
https://github.com/webb-tools/webb.js/blob/063624a5cec34b3387fdc431a8c540346902085d/packages/sdk-mixer/src/wasm-thread.ts#L186

`mixer.add_leaves(mynote.tokenSymbol, mynote.id, leaves, root);` fails with error `11`

Args
```
tokensymbol
EGD
noteid
0

//leaves 
 [Uint8Array(32), Uint8Array(32)]
 0: Uint8Array(32) [97, 184, 145, 124, 13, 37, 73, 198, 243, 165, 215, 5, 186, 179, 3, 99, 13, 63, 22, 8, 177, 149, 213, 196, 144, 174, 13, 217, 226, 208, 215, 8]
 1: Uint8Array(32) [228, 43, 140, 131, 118, 92, 31, 77, 61, 170, 98, 233, 179, 19, 29, 96, 223, 93, 219, 95, 1, 231, 68, 170, 5, 226, 81, 162, 27, 116, 235, 13]
 
// root
 Uint8Array(32) [131, 197, 12, 51, 79, 97, 146, 132, 17, 170, 106, 99, 82, 132, 57, 132, 131, 234, 248, 153, 18, 70, 112, 161, 67, 47, 104, 53, 187, 43, 30, 13]
```

**Comment by shekohex** [comment]
Thanks, I will try to solve some issues in this first: https://github.com/webb-tools/anon/blob/master/wasm-utils/src/lib.rs#L218

And I will use the provided params as a quick test!
